// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqF2c4y2a92VQSoIo4-xOqYhjeHKbSAG0',
    appId: '1:478573598288:web:9ce1234610bdc74d186355',
    messagingSenderId: '478573598288',
    projectId: 'ciac-school',
    authDomain: 'ciac-school.firebaseapp.com',
    storageBucket: 'ciac-school.firebasestorage.app',
    measurementId: 'G-TY5LFF5CZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Popu-gCSuJ1egdGKgv08sMtV5z2nZfc',
    appId: '1:478573598288:android:8c0fc906d5d0d7e6186355',
    messagingSenderId: '478573598288',
    projectId: 'ciac-school',
    storageBucket: 'ciac-school.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3o-7gdKk-z3BIYpMl5r22_trDiKmWNg',
    appId: '1:478573598288:ios:344ba48e53f8cd84186355',
    messagingSenderId: '478573598288',
    projectId: 'ciac-school',
    storageBucket: 'ciac-school.firebasestorage.app',
    iosBundleId: 'com.example.ciacShcool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3o-7gdKk-z3BIYpMl5r22_trDiKmWNg',
    appId: '1:478573598288:ios:344ba48e53f8cd84186355',
    messagingSenderId: '478573598288',
    projectId: 'ciac-school',
    storageBucket: 'ciac-school.firebasestorage.app',
    iosBundleId: 'com.example.ciacShcool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqF2c4y2a92VQSoIo4-xOqYhjeHKbSAG0',
    appId: '1:478573598288:web:870e51cebd11db90186355',
    messagingSenderId: '478573598288',
    projectId: 'ciac-school',
    authDomain: 'ciac-school.firebaseapp.com',
    storageBucket: 'ciac-school.firebasestorage.app',
    measurementId: 'G-5KN330Q7E9',
  );
}
